version: '3.0'

services:
  web:
    build: .
    command: "rails server -b 0.0.0.0"
    volumes:
      - .:/portal-solar-dev-test
    ports:
      - "3000:3000"
    links:
      - db
    env_file: .env
  db:
    image: postgres
    env_file: .env
